---
- name: Konfigurieren des Load Balancers
  hosts: loadbalancers
  become: true
  roles:
    - nginx
    - prometheus
    - grafana
    - node_exporter
    - alertmanager

- name: Konfigurieren der App-Server
  hosts: app_servers
  become: true
  roles:
    - nodejs
    - node_exporter
    - stress
